/* eslint-disable @typescript-eslint/no-require-imports */
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const BOARD_GAMES = [
  {
    name: "Catan",
    category: "STRATEGY",
    description: "Trade, build, and settle the isle of Catan in this modern classic.",
    publisher: "Kosmos",
    yearPublished: 1995,
    minPlayers: 3,
    maxPlayers: 4,
    playTimeMin: 75,
    complexity: 2.3,
    thumbnailUrl: null,
    bggId: 13,
  },
  {
    name: "Carcassonne",
    category: "TILE_PLACEMENT",
    description: "Place tiles and followers to build medieval landscapes and score points.",
    publisher: "Hans im Glück",
    yearPublished: 2000,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMin: 45,
    complexity: 1.9,
    thumbnailUrl: null,
    bggId: 822,
  },
  {
    name: "Pandemic",
    category: "COOPERATIVE",
    description: "Work together as a disease-fighting team to stop global outbreaks.",
    publisher: "Z-Man Games",
    yearPublished: 2008,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMin: 45,
    complexity: 2.4,
    thumbnailUrl: null,
    bggId: 30549,
  },
  {
    name: "Ticket to Ride",
    category: "FAMILY",
    description: "Collect sets of train cards to claim railroad routes across the map.",
    publisher: "Days of Wonder",
    yearPublished: 2004,
    minPlayers: 2,
    maxPlayers: 5,
    playTimeMin: 60,
    complexity: 1.8,
    thumbnailUrl: null,
    bggId: 9209,
  },
  {
    name: "Azul",
    category: "TILE_PLACEMENT",
    description: "Draft and place colorful tiles to decorate the walls of the Royal Palace.",
    publisher: "Plan B Games",
    yearPublished: 2017,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMin: 40,
    complexity: 1.8,
    thumbnailUrl: null,
    bggId: 230802,
  },
  {
    name: "Terraforming Mars",
    category: "ENGINE_BUILDING",
    description: "Corporations compete to terraform Mars through project cards and resource management.",
    publisher: "FryxGames",
    yearPublished: 2016,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMin: 120,
    complexity: 3.3,
    thumbnailUrl: null,
    bggId: 167791,
  },
  {
    name: "Codenames",
    category: "PARTY",
    description: "Two teams compete to identify their agents with one-word clues.",
    publisher: "Czech Games Edition",
    yearPublished: 2015,
    minPlayers: 2,
    maxPlayers: 8,
    playTimeMin: 20,
    complexity: 1.4,
    thumbnailUrl: null,
    bggId: 178900,
  },
  {
    name: "Gloomhaven",
    category: "THEMATIC",
    description: "Epic cooperative campaign with tactical combat and character progression.",
    publisher: "Cephalofair Games",
    yearPublished: 2017,
    minPlayers: 1,
    maxPlayers: 4,
    playTimeMin: 150,
    complexity: 3.9,
    thumbnailUrl: null,
    bggId: 174430,
  },
  {
    name: "Wingspan",
    category: "ENGINE_BUILDING",
    description: "Attract beautiful birds to your wildlife preserves in this award-winning game.",
    publisher: "Stonemaier Games",
    yearPublished: 2019,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMin: 70,
    complexity: 2.4,
    thumbnailUrl: null,
    bggId: 266192,
  },
  {
    name: "7 Wonders",
    category: "SET_COLLECTION",
    description: "Draft cards to build structures, develop science, and erect wonders.",
    publisher: "Repos Production",
    yearPublished: 2010,
    minPlayers: 3,
    maxPlayers: 7,
    playTimeMin: 40,
    complexity: 2.3,
    thumbnailUrl: null,
    bggId: 68448,
  },
  {
    name: "Splendor",
    category: "SET_COLLECTION",
    description: "Collect gems and build your trading empire to attract noble patrons.",
    publisher: "Space Cowboys",
    yearPublished: 2014,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMin: 30,
    complexity: 1.8,
    thumbnailUrl: null,
    bggId: 148228,
  },
  {
    name: "Dixit",
    category: "PARTY",
    description: "Use imagination and clues to guess which surreal artwork matches the storyteller's hint.",
    publisher: "Libellud",
    yearPublished: 2008,
    minPlayers: 3,
    maxPlayers: 6,
    playTimeMin: 30,
    complexity: 1.2,
    thumbnailUrl: null,
    bggId: 39856,
  },
  {
    name: "Dominion",
    category: "CARD_GAME",
    description: "Build a deck from a shared market to accumulate victory points and claim the throne.",
    publisher: "Rio Grande Games",
    yearPublished: 2008,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMin: 45,
    complexity: 2.4,
    thumbnailUrl: null,
    bggId: 36218,
  },
  {
    name: "Scythe",
    category: "AREA_CONTROL",
    description: "Lead your faction in an alternate 1920s Europe with mechs, farms, and territory control.",
    publisher: "Stonemaier Games",
    yearPublished: 2016,
    minPlayers: 1,
    maxPlayers: 5,
    playTimeMin: 120,
    complexity: 3.4,
    thumbnailUrl: null,
    bggId: 169786,
  },
  {
    name: "Root",
    category: "AREA_CONTROL",
    description: "Asymmetric woodland warfare featuring adorable yet ruthless animal factions.",
    publisher: "Leder Games",
    yearPublished: 2018,
    minPlayers: 2,
    maxPlayers: 4,
    playTimeMin: 90,
    complexity: 3.7,
    thumbnailUrl: null,
    bggId: 237182,
  },
  {
    name: "Twilight Imperium: Fourth Edition",
    category: "WAR",
    description: "Command massive fleets, forge alliances, and vie for galactic domination.",
    publisher: "Fantasy Flight Games",
    yearPublished: 2017,
    minPlayers: 3,
    maxPlayers: 6,
    playTimeMin: 240,
    complexity: 4.3,
    thumbnailUrl: null,
    bggId: 233078,
  },
  {
    name: "Risk",
    category: "WAR",
    description: "Classic world domination with armies, dice battles, and territorial control.",
    publisher: "Hasbro",
    yearPublished: 1959,
    minPlayers: 2,
    maxPlayers: 6,
    playTimeMin: 120,
    complexity: 2.1,
    thumbnailUrl: null,
    bggId: 181,
  },
  {
    name: "Monopoly",
    category: "FAMILY",
    description: "Buy, trade, and develop properties to bankrupt your opponents.",
    publisher: "Hasbro",
    yearPublished: 1935,
    minPlayers: 2,
    maxPlayers: 6,
    playTimeMin: 120,
    complexity: 1.7,
    thumbnailUrl: null,
    bggId: 1406,
  },
  {
    name: "Chess",
    category: "ABSTRACT",
    description: "Two-player strategic classic featuring kings, queens, and tactical maneuvers.",
    publisher: "Public domain",
    yearPublished: 1475,
    minPlayers: 2,
    maxPlayers: 2,
    playTimeMin: 60,
    complexity: 3.5,
    thumbnailUrl: null,
    bggId: 171,
  },
  {
    name: "Clue",
    category: "DEDUCTION",
    description: "Solve the murder mystery by deducing the suspect, weapon, and location.",
    publisher: "Hasbro",
    yearPublished: 1949,
    minPlayers: 3,
    maxPlayers: 6,
    playTimeMin: 45,
    complexity: 1.8,
    thumbnailUrl: null,
    bggId: 1294,
  },
];

async function main() {
  for (const game of BOARD_GAMES) {
    await prisma.boardGame.upsert({
      where: { bggId: game.bggId },
      update: {
        category: game.category,
        description: game.description,
        publisher: game.publisher,
        yearPublished: game.yearPublished,
        minPlayers: game.minPlayers,
        maxPlayers: game.maxPlayers,
        playTimeMin: game.playTimeMin,
        complexity: game.complexity,
        thumbnailUrl: game.thumbnailUrl,
        name: game.name,
      },
      create: {
        ...game,
      },
    });
  }
}

main()
  .then(async () => {
    console.log(`Seeded ${BOARD_GAMES.length} board games.`);
  })
  .catch(async (error) => {
    console.error("Seeding failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

